// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCetyf4z8cfs6jvieBE6W68AG_3ggOEW48',
    appId: '1:306431187598:web:fb16e3c8cd86e6a43d07df',
    messagingSenderId: '306431187598',
    projectId: 'app-pontos-dev',
    authDomain: 'app-pontos-dev.firebaseapp.com',
    storageBucket: 'app-pontos-dev.firebasestorage.app',
    measurementId: 'G-HH4ZMRE5Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbNnW0zRTC5FpYBi7oza5T_dTuUWe9W2s',
    appId: '1:306431187598:android:f10763c6226c3f5c3d07df',
    messagingSenderId: '306431187598',
    projectId: 'app-pontos-dev',
    storageBucket: 'app-pontos-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHmqoaWif94fZFtS0YKXkmvHgvWR0oL3M',
    appId: '1:306431187598:ios:f5ed018edb20eb1b3d07df',
    messagingSenderId: '306431187598',
    projectId: 'app-pontos-dev',
    storageBucket: 'app-pontos-dev.firebasestorage.app',
    iosClientId: '306431187598-b8chtu2n08g3c8pnofr7hh0cr9kv3e86.apps.googleusercontent.com',
    iosBundleId: 'com.example.ritmistasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHmqoaWif94fZFtS0YKXkmvHgvWR0oL3M',
    appId: '1:306431187598:ios:f5ed018edb20eb1b3d07df',
    messagingSenderId: '306431187598',
    projectId: 'app-pontos-dev',
    storageBucket: 'app-pontos-dev.firebasestorage.app',
    iosClientId: '306431187598-b8chtu2n08g3c8pnofr7hh0cr9kv3e86.apps.googleusercontent.com',
    iosBundleId: 'com.example.ritmistasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCetyf4z8cfs6jvieBE6W68AG_3ggOEW48',
    appId: '1:306431187598:web:b2514d1975d364a53d07df',
    messagingSenderId: '306431187598',
    projectId: 'app-pontos-dev',
    authDomain: 'app-pontos-dev.firebaseapp.com',
    storageBucket: 'app-pontos-dev.firebasestorage.app',
    measurementId: 'G-2GV1JRGH54',
  );
}
